/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ocean.proxy.thrift.entity;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum AdPubAction implements org.apache.thrift.TEnum {
  EN_AD_ERROR_ST(0),
  EN_AD_WAIT_CHECK(1),
  EN_AD_WAIT_ONLINE(2),
  EN_AD_ONLINE(3),
  EN_AD_PUTDOWN(4),
  EN_AD_NOPASS(5);

  private final int value;

  private AdPubAction(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static AdPubAction findByValue(int value) { 
    switch (value) {
      case 0:
        return EN_AD_ERROR_ST;
      case 1:
        return EN_AD_WAIT_CHECK;
      case 2:
        return EN_AD_WAIT_ONLINE;
      case 3:
        return EN_AD_ONLINE;
      case 4:
        return EN_AD_PUTDOWN;
      case 5:
        return EN_AD_NOPASS;
      default:
        return null;
    }
  }
}
