/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ocean.proxy.thrift.entity;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum AdSrcType implements org.apache.thrift.TEnum {
  AD_SELF(0),
  AD_THIRD(1),
  AD_THIRD_NOTICE(2);

  private final int value;

  private AdSrcType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static AdSrcType findByValue(int value) { 
    switch (value) {
      case 0:
        return AD_SELF;
      case 1:
        return AD_THIRD;
      case 2:
        return AD_THIRD_NOTICE;
      default:
        return null;
    }
  }
}
