/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ocean.proxy.thrift.entity;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2017-1-13")
public class AdUserInfo implements org.apache.thrift.TBase<AdUserInfo, AdUserInfo._Fields>, java.io.Serializable, Cloneable, Comparable<AdUserInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("AdUserInfo");

  private static final org.apache.thrift.protocol.TField IMEI_FIELD_DESC = new org.apache.thrift.protocol.TField("imei", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField OS_FIELD_DESC = new org.apache.thrift.protocol.TField("os", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField OSVERSION_FIELD_DESC = new org.apache.thrift.protocol.TField("osversion", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField PHONEMODEL_FIELD_DESC = new org.apache.thrift.protocol.TField("phonemodel", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField MOBILE_FIELD_DESC = new org.apache.thrift.protocol.TField("mobile", org.apache.thrift.protocol.TType.STRING, (short)5);
  private static final org.apache.thrift.protocol.TField CLIENT_IP_FIELD_DESC = new org.apache.thrift.protocol.TField("client_ip", org.apache.thrift.protocol.TType.STRING, (short)6);
  private static final org.apache.thrift.protocol.TField CITY_FIELD_DESC = new org.apache.thrift.protocol.TField("city", org.apache.thrift.protocol.TType.STRING, (short)7);
  private static final org.apache.thrift.protocol.TField LON_FIELD_DESC = new org.apache.thrift.protocol.TField("lon", org.apache.thrift.protocol.TType.STRING, (short)8);
  private static final org.apache.thrift.protocol.TField LAT_FIELD_DESC = new org.apache.thrift.protocol.TField("lat", org.apache.thrift.protocol.TType.STRING, (short)9);
  private static final org.apache.thrift.protocol.TField UA_FIELD_DESC = new org.apache.thrift.protocol.TField("ua", org.apache.thrift.protocol.TType.STRING, (short)10);
  private static final org.apache.thrift.protocol.TField AAID_FIELD_DESC = new org.apache.thrift.protocol.TField("aaid", org.apache.thrift.protocol.TType.STRING, (short)11);
  private static final org.apache.thrift.protocol.TField ADID_FIELD_DESC = new org.apache.thrift.protocol.TField("adid", org.apache.thrift.protocol.TType.STRING, (short)12);
  private static final org.apache.thrift.protocol.TField IDFA_FIELD_DESC = new org.apache.thrift.protocol.TField("idfa", org.apache.thrift.protocol.TType.STRING, (short)13);
  private static final org.apache.thrift.protocol.TField BRAND_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("brand_id", org.apache.thrift.protocol.TType.STRING, (short)14);
  private static final org.apache.thrift.protocol.TField BRAND_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("brand_name", org.apache.thrift.protocol.TType.STRING, (short)15);
  private static final org.apache.thrift.protocol.TField DEVICE_HEIGHT_FIELD_DESC = new org.apache.thrift.protocol.TField("device_height", org.apache.thrift.protocol.TType.I32, (short)16);
  private static final org.apache.thrift.protocol.TField DEVICE_WIDTH_FIELD_DESC = new org.apache.thrift.protocol.TField("device_width", org.apache.thrift.protocol.TType.I32, (short)17);
  private static final org.apache.thrift.protocol.TField MAC_FIELD_DESC = new org.apache.thrift.protocol.TField("mac", org.apache.thrift.protocol.TType.STRING, (short)18);
  private static final org.apache.thrift.protocol.TField IMSI_FIELD_DESC = new org.apache.thrift.protocol.TField("imsi", org.apache.thrift.protocol.TType.STRING, (short)19);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new AdUserInfoStandardSchemeFactory());
    schemes.put(TupleScheme.class, new AdUserInfoTupleSchemeFactory());
  }

  public String imei; // optional
  public String os; // optional
  public String osversion; // optional
  public String phonemodel; // optional
  public String mobile; // optional
  public String client_ip; // optional
  public String city; // optional
  public String lon; // optional
  public String lat; // optional
  public String ua; // optional
  public String aaid; // optional
  public String adid; // optional
  public String idfa; // optional
  public String brand_id; // optional
  public String brand_name; // optional
  public int device_height; // optional
  public int device_width; // optional
  public String mac; // optional
  public String imsi; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    IMEI((short)1, "imei"),
    OS((short)2, "os"),
    OSVERSION((short)3, "osversion"),
    PHONEMODEL((short)4, "phonemodel"),
    MOBILE((short)5, "mobile"),
    CLIENT_IP((short)6, "client_ip"),
    CITY((short)7, "city"),
    LON((short)8, "lon"),
    LAT((short)9, "lat"),
    UA((short)10, "ua"),
    AAID((short)11, "aaid"),
    ADID((short)12, "adid"),
    IDFA((short)13, "idfa"),
    BRAND_ID((short)14, "brand_id"),
    BRAND_NAME((short)15, "brand_name"),
    DEVICE_HEIGHT((short)16, "device_height"),
    DEVICE_WIDTH((short)17, "device_width"),
    MAC((short)18, "mac"),
    IMSI((short)19, "imsi");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // IMEI
          return IMEI;
        case 2: // OS
          return OS;
        case 3: // OSVERSION
          return OSVERSION;
        case 4: // PHONEMODEL
          return PHONEMODEL;
        case 5: // MOBILE
          return MOBILE;
        case 6: // CLIENT_IP
          return CLIENT_IP;
        case 7: // CITY
          return CITY;
        case 8: // LON
          return LON;
        case 9: // LAT
          return LAT;
        case 10: // UA
          return UA;
        case 11: // AAID
          return AAID;
        case 12: // ADID
          return ADID;
        case 13: // IDFA
          return IDFA;
        case 14: // BRAND_ID
          return BRAND_ID;
        case 15: // BRAND_NAME
          return BRAND_NAME;
        case 16: // DEVICE_HEIGHT
          return DEVICE_HEIGHT;
        case 17: // DEVICE_WIDTH
          return DEVICE_WIDTH;
        case 18: // MAC
          return MAC;
        case 19: // IMSI
          return IMSI;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __DEVICE_HEIGHT_ISSET_ID = 0;
  private static final int __DEVICE_WIDTH_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.IMEI,_Fields.OS,_Fields.OSVERSION,_Fields.PHONEMODEL,_Fields.MOBILE,_Fields.CLIENT_IP,_Fields.CITY,_Fields.LON,_Fields.LAT,_Fields.UA,_Fields.AAID,_Fields.ADID,_Fields.IDFA,_Fields.BRAND_ID,_Fields.BRAND_NAME,_Fields.DEVICE_HEIGHT,_Fields.DEVICE_WIDTH,_Fields.MAC,_Fields.IMSI};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.IMEI, new org.apache.thrift.meta_data.FieldMetaData("imei", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.OS, new org.apache.thrift.meta_data.FieldMetaData("os", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.OSVERSION, new org.apache.thrift.meta_data.FieldMetaData("osversion", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PHONEMODEL, new org.apache.thrift.meta_data.FieldMetaData("phonemodel", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.MOBILE, new org.apache.thrift.meta_data.FieldMetaData("mobile", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CLIENT_IP, new org.apache.thrift.meta_data.FieldMetaData("client_ip", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CITY, new org.apache.thrift.meta_data.FieldMetaData("city", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.LON, new org.apache.thrift.meta_data.FieldMetaData("lon", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.LAT, new org.apache.thrift.meta_data.FieldMetaData("lat", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.UA, new org.apache.thrift.meta_data.FieldMetaData("ua", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.AAID, new org.apache.thrift.meta_data.FieldMetaData("aaid", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ADID, new org.apache.thrift.meta_data.FieldMetaData("adid", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.IDFA, new org.apache.thrift.meta_data.FieldMetaData("idfa", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.BRAND_ID, new org.apache.thrift.meta_data.FieldMetaData("brand_id", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.BRAND_NAME, new org.apache.thrift.meta_data.FieldMetaData("brand_name", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DEVICE_HEIGHT, new org.apache.thrift.meta_data.FieldMetaData("device_height", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.DEVICE_WIDTH, new org.apache.thrift.meta_data.FieldMetaData("device_width", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.MAC, new org.apache.thrift.meta_data.FieldMetaData("mac", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.IMSI, new org.apache.thrift.meta_data.FieldMetaData("imsi", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(AdUserInfo.class, metaDataMap);
  }

  public AdUserInfo() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public AdUserInfo(AdUserInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetImei()) {
      this.imei = other.imei;
    }
    if (other.isSetOs()) {
      this.os = other.os;
    }
    if (other.isSetOsversion()) {
      this.osversion = other.osversion;
    }
    if (other.isSetPhonemodel()) {
      this.phonemodel = other.phonemodel;
    }
    if (other.isSetMobile()) {
      this.mobile = other.mobile;
    }
    if (other.isSetClient_ip()) {
      this.client_ip = other.client_ip;
    }
    if (other.isSetCity()) {
      this.city = other.city;
    }
    if (other.isSetLon()) {
      this.lon = other.lon;
    }
    if (other.isSetLat()) {
      this.lat = other.lat;
    }
    if (other.isSetUa()) {
      this.ua = other.ua;
    }
    if (other.isSetAaid()) {
      this.aaid = other.aaid;
    }
    if (other.isSetAdid()) {
      this.adid = other.adid;
    }
    if (other.isSetIdfa()) {
      this.idfa = other.idfa;
    }
    if (other.isSetBrand_id()) {
      this.brand_id = other.brand_id;
    }
    if (other.isSetBrand_name()) {
      this.brand_name = other.brand_name;
    }
    this.device_height = other.device_height;
    this.device_width = other.device_width;
    if (other.isSetMac()) {
      this.mac = other.mac;
    }
    if (other.isSetImsi()) {
      this.imsi = other.imsi;
    }
  }

  public AdUserInfo deepCopy() {
    return new AdUserInfo(this);
  }

  public void clear() {
    this.imei = null;
    this.os = null;
    this.osversion = null;
    this.phonemodel = null;
    this.mobile = null;
    this.client_ip = null;
    this.city = null;
    this.lon = null;
    this.lat = null;
    this.ua = null;
    this.aaid = null;
    this.adid = null;
    this.idfa = null;
    this.brand_id = null;
    this.brand_name = null;
    setDevice_heightIsSet(false);
    this.device_height = 0;
    setDevice_widthIsSet(false);
    this.device_width = 0;
    this.mac = null;
    this.imsi = null;
  }

  public String getImei() {
    return this.imei;
  }

  public AdUserInfo setImei(String imei) {
    this.imei = imei;
    return this;
  }

  public void unsetImei() {
    this.imei = null;
  }

  /** Returns true if field imei is set (has been assigned a value) and false otherwise */
  public boolean isSetImei() {
    return this.imei != null;
  }

  public void setImeiIsSet(boolean value) {
    if (!value) {
      this.imei = null;
    }
  }

  public String getOs() {
    return this.os;
  }

  public AdUserInfo setOs(String os) {
    this.os = os;
    return this;
  }

  public void unsetOs() {
    this.os = null;
  }

  /** Returns true if field os is set (has been assigned a value) and false otherwise */
  public boolean isSetOs() {
    return this.os != null;
  }

  public void setOsIsSet(boolean value) {
    if (!value) {
      this.os = null;
    }
  }

  public String getOsversion() {
    return this.osversion;
  }

  public AdUserInfo setOsversion(String osversion) {
    this.osversion = osversion;
    return this;
  }

  public void unsetOsversion() {
    this.osversion = null;
  }

  /** Returns true if field osversion is set (has been assigned a value) and false otherwise */
  public boolean isSetOsversion() {
    return this.osversion != null;
  }

  public void setOsversionIsSet(boolean value) {
    if (!value) {
      this.osversion = null;
    }
  }

  public String getPhonemodel() {
    return this.phonemodel;
  }

  public AdUserInfo setPhonemodel(String phonemodel) {
    this.phonemodel = phonemodel;
    return this;
  }

  public void unsetPhonemodel() {
    this.phonemodel = null;
  }

  /** Returns true if field phonemodel is set (has been assigned a value) and false otherwise */
  public boolean isSetPhonemodel() {
    return this.phonemodel != null;
  }

  public void setPhonemodelIsSet(boolean value) {
    if (!value) {
      this.phonemodel = null;
    }
  }

  public String getMobile() {
    return this.mobile;
  }

  public AdUserInfo setMobile(String mobile) {
    this.mobile = mobile;
    return this;
  }

  public void unsetMobile() {
    this.mobile = null;
  }

  /** Returns true if field mobile is set (has been assigned a value) and false otherwise */
  public boolean isSetMobile() {
    return this.mobile != null;
  }

  public void setMobileIsSet(boolean value) {
    if (!value) {
      this.mobile = null;
    }
  }

  public String getClient_ip() {
    return this.client_ip;
  }

  public AdUserInfo setClient_ip(String client_ip) {
    this.client_ip = client_ip;
    return this;
  }

  public void unsetClient_ip() {
    this.client_ip = null;
  }

  /** Returns true if field client_ip is set (has been assigned a value) and false otherwise */
  public boolean isSetClient_ip() {
    return this.client_ip != null;
  }

  public void setClient_ipIsSet(boolean value) {
    if (!value) {
      this.client_ip = null;
    }
  }

  public String getCity() {
    return this.city;
  }

  public AdUserInfo setCity(String city) {
    this.city = city;
    return this;
  }

  public void unsetCity() {
    this.city = null;
  }

  /** Returns true if field city is set (has been assigned a value) and false otherwise */
  public boolean isSetCity() {
    return this.city != null;
  }

  public void setCityIsSet(boolean value) {
    if (!value) {
      this.city = null;
    }
  }

  public String getLon() {
    return this.lon;
  }

  public AdUserInfo setLon(String lon) {
    this.lon = lon;
    return this;
  }

  public void unsetLon() {
    this.lon = null;
  }

  /** Returns true if field lon is set (has been assigned a value) and false otherwise */
  public boolean isSetLon() {
    return this.lon != null;
  }

  public void setLonIsSet(boolean value) {
    if (!value) {
      this.lon = null;
    }
  }

  public String getLat() {
    return this.lat;
  }

  public AdUserInfo setLat(String lat) {
    this.lat = lat;
    return this;
  }

  public void unsetLat() {
    this.lat = null;
  }

  /** Returns true if field lat is set (has been assigned a value) and false otherwise */
  public boolean isSetLat() {
    return this.lat != null;
  }

  public void setLatIsSet(boolean value) {
    if (!value) {
      this.lat = null;
    }
  }

  public String getUa() {
    return this.ua;
  }

  public AdUserInfo setUa(String ua) {
    this.ua = ua;
    return this;
  }

  public void unsetUa() {
    this.ua = null;
  }

  /** Returns true if field ua is set (has been assigned a value) and false otherwise */
  public boolean isSetUa() {
    return this.ua != null;
  }

  public void setUaIsSet(boolean value) {
    if (!value) {
      this.ua = null;
    }
  }

  public String getAaid() {
    return this.aaid;
  }

  public AdUserInfo setAaid(String aaid) {
    this.aaid = aaid;
    return this;
  }

  public void unsetAaid() {
    this.aaid = null;
  }

  /** Returns true if field aaid is set (has been assigned a value) and false otherwise */
  public boolean isSetAaid() {
    return this.aaid != null;
  }

  public void setAaidIsSet(boolean value) {
    if (!value) {
      this.aaid = null;
    }
  }

  public String getAdid() {
    return this.adid;
  }

  public AdUserInfo setAdid(String adid) {
    this.adid = adid;
    return this;
  }

  public void unsetAdid() {
    this.adid = null;
  }

  /** Returns true if field adid is set (has been assigned a value) and false otherwise */
  public boolean isSetAdid() {
    return this.adid != null;
  }

  public void setAdidIsSet(boolean value) {
    if (!value) {
      this.adid = null;
    }
  }

  public String getIdfa() {
    return this.idfa;
  }

  public AdUserInfo setIdfa(String idfa) {
    this.idfa = idfa;
    return this;
  }

  public void unsetIdfa() {
    this.idfa = null;
  }

  /** Returns true if field idfa is set (has been assigned a value) and false otherwise */
  public boolean isSetIdfa() {
    return this.idfa != null;
  }

  public void setIdfaIsSet(boolean value) {
    if (!value) {
      this.idfa = null;
    }
  }

  public String getBrand_id() {
    return this.brand_id;
  }

  public AdUserInfo setBrand_id(String brand_id) {
    this.brand_id = brand_id;
    return this;
  }

  public void unsetBrand_id() {
    this.brand_id = null;
  }

  /** Returns true if field brand_id is set (has been assigned a value) and false otherwise */
  public boolean isSetBrand_id() {
    return this.brand_id != null;
  }

  public void setBrand_idIsSet(boolean value) {
    if (!value) {
      this.brand_id = null;
    }
  }

  public String getBrand_name() {
    return this.brand_name;
  }

  public AdUserInfo setBrand_name(String brand_name) {
    this.brand_name = brand_name;
    return this;
  }

  public void unsetBrand_name() {
    this.brand_name = null;
  }

  /** Returns true if field brand_name is set (has been assigned a value) and false otherwise */
  public boolean isSetBrand_name() {
    return this.brand_name != null;
  }

  public void setBrand_nameIsSet(boolean value) {
    if (!value) {
      this.brand_name = null;
    }
  }

  public int getDevice_height() {
    return this.device_height;
  }

  public AdUserInfo setDevice_height(int device_height) {
    this.device_height = device_height;
    setDevice_heightIsSet(true);
    return this;
  }

  public void unsetDevice_height() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __DEVICE_HEIGHT_ISSET_ID);
  }

  /** Returns true if field device_height is set (has been assigned a value) and false otherwise */
  public boolean isSetDevice_height() {
    return EncodingUtils.testBit(__isset_bitfield, __DEVICE_HEIGHT_ISSET_ID);
  }

  public void setDevice_heightIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __DEVICE_HEIGHT_ISSET_ID, value);
  }

  public int getDevice_width() {
    return this.device_width;
  }

  public AdUserInfo setDevice_width(int device_width) {
    this.device_width = device_width;
    setDevice_widthIsSet(true);
    return this;
  }

  public void unsetDevice_width() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __DEVICE_WIDTH_ISSET_ID);
  }

  /** Returns true if field device_width is set (has been assigned a value) and false otherwise */
  public boolean isSetDevice_width() {
    return EncodingUtils.testBit(__isset_bitfield, __DEVICE_WIDTH_ISSET_ID);
  }

  public void setDevice_widthIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __DEVICE_WIDTH_ISSET_ID, value);
  }

  public String getMac() {
    return this.mac;
  }

  public AdUserInfo setMac(String mac) {
    this.mac = mac;
    return this;
  }

  public void unsetMac() {
    this.mac = null;
  }

  /** Returns true if field mac is set (has been assigned a value) and false otherwise */
  public boolean isSetMac() {
    return this.mac != null;
  }

  public void setMacIsSet(boolean value) {
    if (!value) {
      this.mac = null;
    }
  }

  public String getImsi() {
    return this.imsi;
  }

  public AdUserInfo setImsi(String imsi) {
    this.imsi = imsi;
    return this;
  }

  public void unsetImsi() {
    this.imsi = null;
  }

  /** Returns true if field imsi is set (has been assigned a value) and false otherwise */
  public boolean isSetImsi() {
    return this.imsi != null;
  }

  public void setImsiIsSet(boolean value) {
    if (!value) {
      this.imsi = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case IMEI:
      if (value == null) {
        unsetImei();
      } else {
        setImei((String)value);
      }
      break;

    case OS:
      if (value == null) {
        unsetOs();
      } else {
        setOs((String)value);
      }
      break;

    case OSVERSION:
      if (value == null) {
        unsetOsversion();
      } else {
        setOsversion((String)value);
      }
      break;

    case PHONEMODEL:
      if (value == null) {
        unsetPhonemodel();
      } else {
        setPhonemodel((String)value);
      }
      break;

    case MOBILE:
      if (value == null) {
        unsetMobile();
      } else {
        setMobile((String)value);
      }
      break;

    case CLIENT_IP:
      if (value == null) {
        unsetClient_ip();
      } else {
        setClient_ip((String)value);
      }
      break;

    case CITY:
      if (value == null) {
        unsetCity();
      } else {
        setCity((String)value);
      }
      break;

    case LON:
      if (value == null) {
        unsetLon();
      } else {
        setLon((String)value);
      }
      break;

    case LAT:
      if (value == null) {
        unsetLat();
      } else {
        setLat((String)value);
      }
      break;

    case UA:
      if (value == null) {
        unsetUa();
      } else {
        setUa((String)value);
      }
      break;

    case AAID:
      if (value == null) {
        unsetAaid();
      } else {
        setAaid((String)value);
      }
      break;

    case ADID:
      if (value == null) {
        unsetAdid();
      } else {
        setAdid((String)value);
      }
      break;

    case IDFA:
      if (value == null) {
        unsetIdfa();
      } else {
        setIdfa((String)value);
      }
      break;

    case BRAND_ID:
      if (value == null) {
        unsetBrand_id();
      } else {
        setBrand_id((String)value);
      }
      break;

    case BRAND_NAME:
      if (value == null) {
        unsetBrand_name();
      } else {
        setBrand_name((String)value);
      }
      break;

    case DEVICE_HEIGHT:
      if (value == null) {
        unsetDevice_height();
      } else {
        setDevice_height((Integer)value);
      }
      break;

    case DEVICE_WIDTH:
      if (value == null) {
        unsetDevice_width();
      } else {
        setDevice_width((Integer)value);
      }
      break;

    case MAC:
      if (value == null) {
        unsetMac();
      } else {
        setMac((String)value);
      }
      break;

    case IMSI:
      if (value == null) {
        unsetImsi();
      } else {
        setImsi((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case IMEI:
      return getImei();

    case OS:
      return getOs();

    case OSVERSION:
      return getOsversion();

    case PHONEMODEL:
      return getPhonemodel();

    case MOBILE:
      return getMobile();

    case CLIENT_IP:
      return getClient_ip();

    case CITY:
      return getCity();

    case LON:
      return getLon();

    case LAT:
      return getLat();

    case UA:
      return getUa();

    case AAID:
      return getAaid();

    case ADID:
      return getAdid();

    case IDFA:
      return getIdfa();

    case BRAND_ID:
      return getBrand_id();

    case BRAND_NAME:
      return getBrand_name();

    case DEVICE_HEIGHT:
      return Integer.valueOf(getDevice_height());

    case DEVICE_WIDTH:
      return Integer.valueOf(getDevice_width());

    case MAC:
      return getMac();

    case IMSI:
      return getImsi();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case IMEI:
      return isSetImei();
    case OS:
      return isSetOs();
    case OSVERSION:
      return isSetOsversion();
    case PHONEMODEL:
      return isSetPhonemodel();
    case MOBILE:
      return isSetMobile();
    case CLIENT_IP:
      return isSetClient_ip();
    case CITY:
      return isSetCity();
    case LON:
      return isSetLon();
    case LAT:
      return isSetLat();
    case UA:
      return isSetUa();
    case AAID:
      return isSetAaid();
    case ADID:
      return isSetAdid();
    case IDFA:
      return isSetIdfa();
    case BRAND_ID:
      return isSetBrand_id();
    case BRAND_NAME:
      return isSetBrand_name();
    case DEVICE_HEIGHT:
      return isSetDevice_height();
    case DEVICE_WIDTH:
      return isSetDevice_width();
    case MAC:
      return isSetMac();
    case IMSI:
      return isSetImsi();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof AdUserInfo)
      return this.equals((AdUserInfo)that);
    return false;
  }

  public boolean equals(AdUserInfo that) {
    if (that == null)
      return false;

    boolean this_present_imei = true && this.isSetImei();
    boolean that_present_imei = true && that.isSetImei();
    if (this_present_imei || that_present_imei) {
      if (!(this_present_imei && that_present_imei))
        return false;
      if (!this.imei.equals(that.imei))
        return false;
    }

    boolean this_present_os = true && this.isSetOs();
    boolean that_present_os = true && that.isSetOs();
    if (this_present_os || that_present_os) {
      if (!(this_present_os && that_present_os))
        return false;
      if (!this.os.equals(that.os))
        return false;
    }

    boolean this_present_osversion = true && this.isSetOsversion();
    boolean that_present_osversion = true && that.isSetOsversion();
    if (this_present_osversion || that_present_osversion) {
      if (!(this_present_osversion && that_present_osversion))
        return false;
      if (!this.osversion.equals(that.osversion))
        return false;
    }

    boolean this_present_phonemodel = true && this.isSetPhonemodel();
    boolean that_present_phonemodel = true && that.isSetPhonemodel();
    if (this_present_phonemodel || that_present_phonemodel) {
      if (!(this_present_phonemodel && that_present_phonemodel))
        return false;
      if (!this.phonemodel.equals(that.phonemodel))
        return false;
    }

    boolean this_present_mobile = true && this.isSetMobile();
    boolean that_present_mobile = true && that.isSetMobile();
    if (this_present_mobile || that_present_mobile) {
      if (!(this_present_mobile && that_present_mobile))
        return false;
      if (!this.mobile.equals(that.mobile))
        return false;
    }

    boolean this_present_client_ip = true && this.isSetClient_ip();
    boolean that_present_client_ip = true && that.isSetClient_ip();
    if (this_present_client_ip || that_present_client_ip) {
      if (!(this_present_client_ip && that_present_client_ip))
        return false;
      if (!this.client_ip.equals(that.client_ip))
        return false;
    }

    boolean this_present_city = true && this.isSetCity();
    boolean that_present_city = true && that.isSetCity();
    if (this_present_city || that_present_city) {
      if (!(this_present_city && that_present_city))
        return false;
      if (!this.city.equals(that.city))
        return false;
    }

    boolean this_present_lon = true && this.isSetLon();
    boolean that_present_lon = true && that.isSetLon();
    if (this_present_lon || that_present_lon) {
      if (!(this_present_lon && that_present_lon))
        return false;
      if (!this.lon.equals(that.lon))
        return false;
    }

    boolean this_present_lat = true && this.isSetLat();
    boolean that_present_lat = true && that.isSetLat();
    if (this_present_lat || that_present_lat) {
      if (!(this_present_lat && that_present_lat))
        return false;
      if (!this.lat.equals(that.lat))
        return false;
    }

    boolean this_present_ua = true && this.isSetUa();
    boolean that_present_ua = true && that.isSetUa();
    if (this_present_ua || that_present_ua) {
      if (!(this_present_ua && that_present_ua))
        return false;
      if (!this.ua.equals(that.ua))
        return false;
    }

    boolean this_present_aaid = true && this.isSetAaid();
    boolean that_present_aaid = true && that.isSetAaid();
    if (this_present_aaid || that_present_aaid) {
      if (!(this_present_aaid && that_present_aaid))
        return false;
      if (!this.aaid.equals(that.aaid))
        return false;
    }

    boolean this_present_adid = true && this.isSetAdid();
    boolean that_present_adid = true && that.isSetAdid();
    if (this_present_adid || that_present_adid) {
      if (!(this_present_adid && that_present_adid))
        return false;
      if (!this.adid.equals(that.adid))
        return false;
    }

    boolean this_present_idfa = true && this.isSetIdfa();
    boolean that_present_idfa = true && that.isSetIdfa();
    if (this_present_idfa || that_present_idfa) {
      if (!(this_present_idfa && that_present_idfa))
        return false;
      if (!this.idfa.equals(that.idfa))
        return false;
    }

    boolean this_present_brand_id = true && this.isSetBrand_id();
    boolean that_present_brand_id = true && that.isSetBrand_id();
    if (this_present_brand_id || that_present_brand_id) {
      if (!(this_present_brand_id && that_present_brand_id))
        return false;
      if (!this.brand_id.equals(that.brand_id))
        return false;
    }

    boolean this_present_brand_name = true && this.isSetBrand_name();
    boolean that_present_brand_name = true && that.isSetBrand_name();
    if (this_present_brand_name || that_present_brand_name) {
      if (!(this_present_brand_name && that_present_brand_name))
        return false;
      if (!this.brand_name.equals(that.brand_name))
        return false;
    }

    boolean this_present_device_height = true && this.isSetDevice_height();
    boolean that_present_device_height = true && that.isSetDevice_height();
    if (this_present_device_height || that_present_device_height) {
      if (!(this_present_device_height && that_present_device_height))
        return false;
      if (this.device_height != that.device_height)
        return false;
    }

    boolean this_present_device_width = true && this.isSetDevice_width();
    boolean that_present_device_width = true && that.isSetDevice_width();
    if (this_present_device_width || that_present_device_width) {
      if (!(this_present_device_width && that_present_device_width))
        return false;
      if (this.device_width != that.device_width)
        return false;
    }

    boolean this_present_mac = true && this.isSetMac();
    boolean that_present_mac = true && that.isSetMac();
    if (this_present_mac || that_present_mac) {
      if (!(this_present_mac && that_present_mac))
        return false;
      if (!this.mac.equals(that.mac))
        return false;
    }

    boolean this_present_imsi = true && this.isSetImsi();
    boolean that_present_imsi = true && that.isSetImsi();
    if (this_present_imsi || that_present_imsi) {
      if (!(this_present_imsi && that_present_imsi))
        return false;
      if (!this.imsi.equals(that.imsi))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_imei = true && (isSetImei());
    list.add(present_imei);
    if (present_imei)
      list.add(imei);

    boolean present_os = true && (isSetOs());
    list.add(present_os);
    if (present_os)
      list.add(os);

    boolean present_osversion = true && (isSetOsversion());
    list.add(present_osversion);
    if (present_osversion)
      list.add(osversion);

    boolean present_phonemodel = true && (isSetPhonemodel());
    list.add(present_phonemodel);
    if (present_phonemodel)
      list.add(phonemodel);

    boolean present_mobile = true && (isSetMobile());
    list.add(present_mobile);
    if (present_mobile)
      list.add(mobile);

    boolean present_client_ip = true && (isSetClient_ip());
    list.add(present_client_ip);
    if (present_client_ip)
      list.add(client_ip);

    boolean present_city = true && (isSetCity());
    list.add(present_city);
    if (present_city)
      list.add(city);

    boolean present_lon = true && (isSetLon());
    list.add(present_lon);
    if (present_lon)
      list.add(lon);

    boolean present_lat = true && (isSetLat());
    list.add(present_lat);
    if (present_lat)
      list.add(lat);

    boolean present_ua = true && (isSetUa());
    list.add(present_ua);
    if (present_ua)
      list.add(ua);

    boolean present_aaid = true && (isSetAaid());
    list.add(present_aaid);
    if (present_aaid)
      list.add(aaid);

    boolean present_adid = true && (isSetAdid());
    list.add(present_adid);
    if (present_adid)
      list.add(adid);

    boolean present_idfa = true && (isSetIdfa());
    list.add(present_idfa);
    if (present_idfa)
      list.add(idfa);

    boolean present_brand_id = true && (isSetBrand_id());
    list.add(present_brand_id);
    if (present_brand_id)
      list.add(brand_id);

    boolean present_brand_name = true && (isSetBrand_name());
    list.add(present_brand_name);
    if (present_brand_name)
      list.add(brand_name);

    boolean present_device_height = true && (isSetDevice_height());
    list.add(present_device_height);
    if (present_device_height)
      list.add(device_height);

    boolean present_device_width = true && (isSetDevice_width());
    list.add(present_device_width);
    if (present_device_width)
      list.add(device_width);

    boolean present_mac = true && (isSetMac());
    list.add(present_mac);
    if (present_mac)
      list.add(mac);

    boolean present_imsi = true && (isSetImsi());
    list.add(present_imsi);
    if (present_imsi)
      list.add(imsi);

    return list.hashCode();
  }

  public int compareTo(AdUserInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetImei()).compareTo(other.isSetImei());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetImei()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.imei, other.imei);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetOs()).compareTo(other.isSetOs());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOs()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.os, other.os);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetOsversion()).compareTo(other.isSetOsversion());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOsversion()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.osversion, other.osversion);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPhonemodel()).compareTo(other.isSetPhonemodel());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPhonemodel()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.phonemodel, other.phonemodel);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMobile()).compareTo(other.isSetMobile());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMobile()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.mobile, other.mobile);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetClient_ip()).compareTo(other.isSetClient_ip());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetClient_ip()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.client_ip, other.client_ip);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCity()).compareTo(other.isSetCity());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCity()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.city, other.city);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLon()).compareTo(other.isSetLon());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLon()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.lon, other.lon);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLat()).compareTo(other.isSetLat());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLat()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.lat, other.lat);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUa()).compareTo(other.isSetUa());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUa()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ua, other.ua);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetAaid()).compareTo(other.isSetAaid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAaid()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.aaid, other.aaid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetAdid()).compareTo(other.isSetAdid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAdid()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.adid, other.adid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetIdfa()).compareTo(other.isSetIdfa());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIdfa()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.idfa, other.idfa);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetBrand_id()).compareTo(other.isSetBrand_id());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBrand_id()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.brand_id, other.brand_id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetBrand_name()).compareTo(other.isSetBrand_name());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBrand_name()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.brand_name, other.brand_name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDevice_height()).compareTo(other.isSetDevice_height());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDevice_height()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.device_height, other.device_height);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDevice_width()).compareTo(other.isSetDevice_width());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDevice_width()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.device_width, other.device_width);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMac()).compareTo(other.isSetMac());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMac()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.mac, other.mac);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetImsi()).compareTo(other.isSetImsi());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetImsi()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.imsi, other.imsi);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("AdUserInfo(");
    boolean first = true;

    if (isSetImei()) {
      sb.append("imei:");
      if (this.imei == null) {
        sb.append("null");
      } else {
        sb.append(this.imei);
      }
      first = false;
    }
    if (isSetOs()) {
      if (!first) sb.append(", ");
      sb.append("os:");
      if (this.os == null) {
        sb.append("null");
      } else {
        sb.append(this.os);
      }
      first = false;
    }
    if (isSetOsversion()) {
      if (!first) sb.append(", ");
      sb.append("osversion:");
      if (this.osversion == null) {
        sb.append("null");
      } else {
        sb.append(this.osversion);
      }
      first = false;
    }
    if (isSetPhonemodel()) {
      if (!first) sb.append(", ");
      sb.append("phonemodel:");
      if (this.phonemodel == null) {
        sb.append("null");
      } else {
        sb.append(this.phonemodel);
      }
      first = false;
    }
    if (isSetMobile()) {
      if (!first) sb.append(", ");
      sb.append("mobile:");
      if (this.mobile == null) {
        sb.append("null");
      } else {
        sb.append(this.mobile);
      }
      first = false;
    }
    if (isSetClient_ip()) {
      if (!first) sb.append(", ");
      sb.append("client_ip:");
      if (this.client_ip == null) {
        sb.append("null");
      } else {
        sb.append(this.client_ip);
      }
      first = false;
    }
    if (isSetCity()) {
      if (!first) sb.append(", ");
      sb.append("city:");
      if (this.city == null) {
        sb.append("null");
      } else {
        sb.append(this.city);
      }
      first = false;
    }
    if (isSetLon()) {
      if (!first) sb.append(", ");
      sb.append("lon:");
      if (this.lon == null) {
        sb.append("null");
      } else {
        sb.append(this.lon);
      }
      first = false;
    }
    if (isSetLat()) {
      if (!first) sb.append(", ");
      sb.append("lat:");
      if (this.lat == null) {
        sb.append("null");
      } else {
        sb.append(this.lat);
      }
      first = false;
    }
    if (isSetUa()) {
      if (!first) sb.append(", ");
      sb.append("ua:");
      if (this.ua == null) {
        sb.append("null");
      } else {
        sb.append(this.ua);
      }
      first = false;
    }
    if (isSetAaid()) {
      if (!first) sb.append(", ");
      sb.append("aaid:");
      if (this.aaid == null) {
        sb.append("null");
      } else {
        sb.append(this.aaid);
      }
      first = false;
    }
    if (isSetAdid()) {
      if (!first) sb.append(", ");
      sb.append("adid:");
      if (this.adid == null) {
        sb.append("null");
      } else {
        sb.append(this.adid);
      }
      first = false;
    }
    if (isSetIdfa()) {
      if (!first) sb.append(", ");
      sb.append("idfa:");
      if (this.idfa == null) {
        sb.append("null");
      } else {
        sb.append(this.idfa);
      }
      first = false;
    }
    if (isSetBrand_id()) {
      if (!first) sb.append(", ");
      sb.append("brand_id:");
      if (this.brand_id == null) {
        sb.append("null");
      } else {
        sb.append(this.brand_id);
      }
      first = false;
    }
    if (isSetBrand_name()) {
      if (!first) sb.append(", ");
      sb.append("brand_name:");
      if (this.brand_name == null) {
        sb.append("null");
      } else {
        sb.append(this.brand_name);
      }
      first = false;
    }
    if (isSetDevice_height()) {
      if (!first) sb.append(", ");
      sb.append("device_height:");
      sb.append(this.device_height);
      first = false;
    }
    if (isSetDevice_width()) {
      if (!first) sb.append(", ");
      sb.append("device_width:");
      sb.append(this.device_width);
      first = false;
    }
    if (isSetMac()) {
      if (!first) sb.append(", ");
      sb.append("mac:");
      if (this.mac == null) {
        sb.append("null");
      } else {
        sb.append(this.mac);
      }
      first = false;
    }
    if (isSetImsi()) {
      if (!first) sb.append(", ");
      sb.append("imsi:");
      if (this.imsi == null) {
        sb.append("null");
      } else {
        sb.append(this.imsi);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class AdUserInfoStandardSchemeFactory implements SchemeFactory {
    public AdUserInfoStandardScheme getScheme() {
      return new AdUserInfoStandardScheme();
    }
  }

  private static class AdUserInfoStandardScheme extends StandardScheme<AdUserInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, AdUserInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // IMEI
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.imei = iprot.readString();
              struct.setImeiIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // OS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.os = iprot.readString();
              struct.setOsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // OSVERSION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.osversion = iprot.readString();
              struct.setOsversionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // PHONEMODEL
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.phonemodel = iprot.readString();
              struct.setPhonemodelIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // MOBILE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.mobile = iprot.readString();
              struct.setMobileIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // CLIENT_IP
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.client_ip = iprot.readString();
              struct.setClient_ipIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // CITY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.city = iprot.readString();
              struct.setCityIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // LON
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.lon = iprot.readString();
              struct.setLonIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // LAT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.lat = iprot.readString();
              struct.setLatIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // UA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.ua = iprot.readString();
              struct.setUaIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 11: // AAID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.aaid = iprot.readString();
              struct.setAaidIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 12: // ADID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.adid = iprot.readString();
              struct.setAdidIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 13: // IDFA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.idfa = iprot.readString();
              struct.setIdfaIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 14: // BRAND_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.brand_id = iprot.readString();
              struct.setBrand_idIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 15: // BRAND_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.brand_name = iprot.readString();
              struct.setBrand_nameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 16: // DEVICE_HEIGHT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.device_height = iprot.readI32();
              struct.setDevice_heightIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 17: // DEVICE_WIDTH
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.device_width = iprot.readI32();
              struct.setDevice_widthIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 18: // MAC
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.mac = iprot.readString();
              struct.setMacIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 19: // IMSI
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.imsi = iprot.readString();
              struct.setImsiIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, AdUserInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.imei != null) {
        if (struct.isSetImei()) {
          oprot.writeFieldBegin(IMEI_FIELD_DESC);
          oprot.writeString(struct.imei);
          oprot.writeFieldEnd();
        }
      }
      if (struct.os != null) {
        if (struct.isSetOs()) {
          oprot.writeFieldBegin(OS_FIELD_DESC);
          oprot.writeString(struct.os);
          oprot.writeFieldEnd();
        }
      }
      if (struct.osversion != null) {
        if (struct.isSetOsversion()) {
          oprot.writeFieldBegin(OSVERSION_FIELD_DESC);
          oprot.writeString(struct.osversion);
          oprot.writeFieldEnd();
        }
      }
      if (struct.phonemodel != null) {
        if (struct.isSetPhonemodel()) {
          oprot.writeFieldBegin(PHONEMODEL_FIELD_DESC);
          oprot.writeString(struct.phonemodel);
          oprot.writeFieldEnd();
        }
      }
      if (struct.mobile != null) {
        if (struct.isSetMobile()) {
          oprot.writeFieldBegin(MOBILE_FIELD_DESC);
          oprot.writeString(struct.mobile);
          oprot.writeFieldEnd();
        }
      }
      if (struct.client_ip != null) {
        if (struct.isSetClient_ip()) {
          oprot.writeFieldBegin(CLIENT_IP_FIELD_DESC);
          oprot.writeString(struct.client_ip);
          oprot.writeFieldEnd();
        }
      }
      if (struct.city != null) {
        if (struct.isSetCity()) {
          oprot.writeFieldBegin(CITY_FIELD_DESC);
          oprot.writeString(struct.city);
          oprot.writeFieldEnd();
        }
      }
      if (struct.lon != null) {
        if (struct.isSetLon()) {
          oprot.writeFieldBegin(LON_FIELD_DESC);
          oprot.writeString(struct.lon);
          oprot.writeFieldEnd();
        }
      }
      if (struct.lat != null) {
        if (struct.isSetLat()) {
          oprot.writeFieldBegin(LAT_FIELD_DESC);
          oprot.writeString(struct.lat);
          oprot.writeFieldEnd();
        }
      }
      if (struct.ua != null) {
        if (struct.isSetUa()) {
          oprot.writeFieldBegin(UA_FIELD_DESC);
          oprot.writeString(struct.ua);
          oprot.writeFieldEnd();
        }
      }
      if (struct.aaid != null) {
        if (struct.isSetAaid()) {
          oprot.writeFieldBegin(AAID_FIELD_DESC);
          oprot.writeString(struct.aaid);
          oprot.writeFieldEnd();
        }
      }
      if (struct.adid != null) {
        if (struct.isSetAdid()) {
          oprot.writeFieldBegin(ADID_FIELD_DESC);
          oprot.writeString(struct.adid);
          oprot.writeFieldEnd();
        }
      }
      if (struct.idfa != null) {
        if (struct.isSetIdfa()) {
          oprot.writeFieldBegin(IDFA_FIELD_DESC);
          oprot.writeString(struct.idfa);
          oprot.writeFieldEnd();
        }
      }
      if (struct.brand_id != null) {
        if (struct.isSetBrand_id()) {
          oprot.writeFieldBegin(BRAND_ID_FIELD_DESC);
          oprot.writeString(struct.brand_id);
          oprot.writeFieldEnd();
        }
      }
      if (struct.brand_name != null) {
        if (struct.isSetBrand_name()) {
          oprot.writeFieldBegin(BRAND_NAME_FIELD_DESC);
          oprot.writeString(struct.brand_name);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetDevice_height()) {
        oprot.writeFieldBegin(DEVICE_HEIGHT_FIELD_DESC);
        oprot.writeI32(struct.device_height);
        oprot.writeFieldEnd();
      }
      if (struct.isSetDevice_width()) {
        oprot.writeFieldBegin(DEVICE_WIDTH_FIELD_DESC);
        oprot.writeI32(struct.device_width);
        oprot.writeFieldEnd();
      }
      if (struct.mac != null) {
        if (struct.isSetMac()) {
          oprot.writeFieldBegin(MAC_FIELD_DESC);
          oprot.writeString(struct.mac);
          oprot.writeFieldEnd();
        }
      }
      if (struct.imsi != null) {
        if (struct.isSetImsi()) {
          oprot.writeFieldBegin(IMSI_FIELD_DESC);
          oprot.writeString(struct.imsi);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class AdUserInfoTupleSchemeFactory implements SchemeFactory {
    public AdUserInfoTupleScheme getScheme() {
      return new AdUserInfoTupleScheme();
    }
  }

  private static class AdUserInfoTupleScheme extends TupleScheme<AdUserInfo> {

    public void write(org.apache.thrift.protocol.TProtocol prot, AdUserInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetImei()) {
        optionals.set(0);
      }
      if (struct.isSetOs()) {
        optionals.set(1);
      }
      if (struct.isSetOsversion()) {
        optionals.set(2);
      }
      if (struct.isSetPhonemodel()) {
        optionals.set(3);
      }
      if (struct.isSetMobile()) {
        optionals.set(4);
      }
      if (struct.isSetClient_ip()) {
        optionals.set(5);
      }
      if (struct.isSetCity()) {
        optionals.set(6);
      }
      if (struct.isSetLon()) {
        optionals.set(7);
      }
      if (struct.isSetLat()) {
        optionals.set(8);
      }
      if (struct.isSetUa()) {
        optionals.set(9);
      }
      if (struct.isSetAaid()) {
        optionals.set(10);
      }
      if (struct.isSetAdid()) {
        optionals.set(11);
      }
      if (struct.isSetIdfa()) {
        optionals.set(12);
      }
      if (struct.isSetBrand_id()) {
        optionals.set(13);
      }
      if (struct.isSetBrand_name()) {
        optionals.set(14);
      }
      if (struct.isSetDevice_height()) {
        optionals.set(15);
      }
      if (struct.isSetDevice_width()) {
        optionals.set(16);
      }
      if (struct.isSetMac()) {
        optionals.set(17);
      }
      if (struct.isSetImsi()) {
        optionals.set(18);
      }
      oprot.writeBitSet(optionals, 19);
      if (struct.isSetImei()) {
        oprot.writeString(struct.imei);
      }
      if (struct.isSetOs()) {
        oprot.writeString(struct.os);
      }
      if (struct.isSetOsversion()) {
        oprot.writeString(struct.osversion);
      }
      if (struct.isSetPhonemodel()) {
        oprot.writeString(struct.phonemodel);
      }
      if (struct.isSetMobile()) {
        oprot.writeString(struct.mobile);
      }
      if (struct.isSetClient_ip()) {
        oprot.writeString(struct.client_ip);
      }
      if (struct.isSetCity()) {
        oprot.writeString(struct.city);
      }
      if (struct.isSetLon()) {
        oprot.writeString(struct.lon);
      }
      if (struct.isSetLat()) {
        oprot.writeString(struct.lat);
      }
      if (struct.isSetUa()) {
        oprot.writeString(struct.ua);
      }
      if (struct.isSetAaid()) {
        oprot.writeString(struct.aaid);
      }
      if (struct.isSetAdid()) {
        oprot.writeString(struct.adid);
      }
      if (struct.isSetIdfa()) {
        oprot.writeString(struct.idfa);
      }
      if (struct.isSetBrand_id()) {
        oprot.writeString(struct.brand_id);
      }
      if (struct.isSetBrand_name()) {
        oprot.writeString(struct.brand_name);
      }
      if (struct.isSetDevice_height()) {
        oprot.writeI32(struct.device_height);
      }
      if (struct.isSetDevice_width()) {
        oprot.writeI32(struct.device_width);
      }
      if (struct.isSetMac()) {
        oprot.writeString(struct.mac);
      }
      if (struct.isSetImsi()) {
        oprot.writeString(struct.imsi);
      }
    }

    public void read(org.apache.thrift.protocol.TProtocol prot, AdUserInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(19);
      if (incoming.get(0)) {
        struct.imei = iprot.readString();
        struct.setImeiIsSet(true);
      }
      if (incoming.get(1)) {
        struct.os = iprot.readString();
        struct.setOsIsSet(true);
      }
      if (incoming.get(2)) {
        struct.osversion = iprot.readString();
        struct.setOsversionIsSet(true);
      }
      if (incoming.get(3)) {
        struct.phonemodel = iprot.readString();
        struct.setPhonemodelIsSet(true);
      }
      if (incoming.get(4)) {
        struct.mobile = iprot.readString();
        struct.setMobileIsSet(true);
      }
      if (incoming.get(5)) {
        struct.client_ip = iprot.readString();
        struct.setClient_ipIsSet(true);
      }
      if (incoming.get(6)) {
        struct.city = iprot.readString();
        struct.setCityIsSet(true);
      }
      if (incoming.get(7)) {
        struct.lon = iprot.readString();
        struct.setLonIsSet(true);
      }
      if (incoming.get(8)) {
        struct.lat = iprot.readString();
        struct.setLatIsSet(true);
      }
      if (incoming.get(9)) {
        struct.ua = iprot.readString();
        struct.setUaIsSet(true);
      }
      if (incoming.get(10)) {
        struct.aaid = iprot.readString();
        struct.setAaidIsSet(true);
      }
      if (incoming.get(11)) {
        struct.adid = iprot.readString();
        struct.setAdidIsSet(true);
      }
      if (incoming.get(12)) {
        struct.idfa = iprot.readString();
        struct.setIdfaIsSet(true);
      }
      if (incoming.get(13)) {
        struct.brand_id = iprot.readString();
        struct.setBrand_idIsSet(true);
      }
      if (incoming.get(14)) {
        struct.brand_name = iprot.readString();
        struct.setBrand_nameIsSet(true);
      }
      if (incoming.get(15)) {
        struct.device_height = iprot.readI32();
        struct.setDevice_heightIsSet(true);
      }
      if (incoming.get(16)) {
        struct.device_width = iprot.readI32();
        struct.setDevice_widthIsSet(true);
      }
      if (incoming.get(17)) {
        struct.mac = iprot.readString();
        struct.setMacIsSet(true);
      }
      if (incoming.get(18)) {
        struct.imsi = iprot.readString();
        struct.setImsiIsSet(true);
      }
    }
  }

}

