/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ocean.proxy.thrift.entity;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ProductType implements org.apache.thrift.TEnum {
  APP(1),
  JS(2),
  THIRD(3);

  private final int value;

  private ProductType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ProductType findByValue(int value) { 
    switch (value) {
      case 1:
        return APP;
      case 2:
        return JS;
      case 3:
        return THIRD;
      default:
        return null;
    }
  }
}
